#ifndef _PORT_H_
#define _PORT_H_

#include "platform_types.h"

STATUS API NO_CALLER_SAVED_REGISTERS PortWriteByte(IN UINT16 Port, IN UINT8 Value);

STATUS API NO_CALLER_SAVED_REGISTERS PortWriteWord(IN CONST UINT16 Port, IN CONST UINT16 Value);

STATUS API NO_CALLER_SAVED_REGISTERS PortWriteDoubleWord(IN CONST UINT16 Port, IN CONST UINT32 Value);

STATUS API NO_CALLER_SAVED_REGISTERS PortReadByte(IN CONST UINT16 Port, OUT UINT8 *Value);

STATUS API NO_CALLER_SAVED_REGISTERS PortReadWord(IN CONST UINT16 Port, OUT UINT16 *Value);

STATUS API NO_CALLER_SAVED_REGISTERS PortReadDoubleWord(IN CONST UINT16 Port, OUT UINT32* Value);

#endif /* _PORT_H_ */
